name: Swift

on: [push]

jobs:
  build:
    
    container:
      image: swift:5.1.4

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run tests
      run: swift test -v

    - name: Build Output
      run: swift run -v

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: 'cchmelb-demo'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
        SOURCE_DIR: '.export'      # optional: defaults to entire repository
    
